replicas: 1

global:
  name: echoserver
  namespace: default

rbac:
  create: true
  pspEnabled: false

image:
  repository: sergrua/echoserver
  tag: latest
  pullPolicy: Always
  namespace: default
  backoffLimit: 3
  containerPort: 8080

ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  annotations: {}

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: echoserver.local
    path: /


service:
  type: ClusterIP
  port: 8080
  externalTrafficPolicy: Cluster
  nodePorts: {}
  annotations: {}

extraEnv: {}
resources:      {}
nodeSelector:   {}
tolerations:    []
affinity:       {}
podAnnotations: {}
